Styles/palette
NivaldoFarias/linkr-frontend pull request #44
Opened 2022-06-19 18:48 UTC by NivaldoFarias

Mudança bem significativa no layout!! Por favor testar antes de aprovar

2022-06-19 20:18 UTC, estevamfurtado commented
Como é um commit de styles, eu to checando localmente o que aconteceu e encontrei alguns bugs.

1. Tamanho de referência do feed não tá fixo. No caso de não ter posts ele fica menor.
2. Font family dos elementos do componente Post tá estranho. Cores também.
3. Se o post tem imagem, ele desconfigura bastante e ultrapassa o limite do Feed.
4. O feed está scrollando, mas quando tem muitos posts ele não chega ao final do jeito certo (último post fica cortado pela metade). 

Fotos não estão na ordem:
![Captura de Tela 2022-06-19 às 17 12 54](https://user-images.githubusercontent.com/15219345/174498858-c4b292de-bb07-48b7-9f20-aafb281e3bb9.png)
![Captura de Tela 2022-06-19 às 17 12 59](https://user-images.githubusercontent.com/15219345/174498859-b470495e-8d93-41a6-8884-e57f247f6538.png)
![Captura de Tela 2022-06-19 às 17 13 09](https://user-images.githubusercontent.com/15219345/174498861-b8583402-fe80-43df-87b5-6f50b7d307a9.png)
![Captura de Tela 2022-06-19 às 17 13 24](https://user-images.githubusercontent.com/15219345/174498862-ff21c440-a858-4670-b69d-68c2d6ee8a0a.png)
![Captura de Tela 2022-06-19 às 17 14 12](https://user-images.githubusercontent.com/15219345/174498864-9aabc43d-6297-46c5-b769-0dd77b80435c.png)

2022-06-19 20:20 UTC, estevamfurtado requested changes
Fiz o comentário a partir do teste de uso das alterações de layout.

2022-06-20 02:53 UTC, NivaldoFarias commented
3 dos 4 bugs foram causados por mim durante o merge com a main antes do ultimo commit, parece que a classe ".link" subiu um espaço de brackets >> { }, daí fez com que ela ficasse sem ser utilizada, não aplicando todo os estilos que fiz.

Além de consertar os bugs, consertei alguns bugs na barra de pesquisa e melhorei um pouco o layout básico dele

2022-06-20 12:06 UTC, estevamfurtado approved these changes

2022-06-20 13:33 UTC, merged